source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'

target 'TNKImagePickerController_Example', :exclusive => true do
  pod "TNKImagePickerController", :path => "../"
end

target 'TNKImagePickerController_Tests', :exclusive => true do
  pod "TNKImagePickerController", :path => "../"

  pod 'FBSnapshotTestCase'
end
